name: Deploy to Azure

on: 
  push:

  workflow_dispatch:

jobs:

  Install_CLIs:

    name: "Install Terraform and Azure ClI and Authenticate to Azure"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Repo"
        uses: actions/checkout@v4

      - name: "Install terraform on runner"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "latest"

      - name: "Install Azure Cli"
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
      - name: "Log into Azure"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          secret-id: ${{ secrets.AZURE_SECRET_ID }}
    

      - name: "Run Terraform init"
        run: terraform init

      - name: "Run Terraform plan"
        run: terraform plan
      
      - name: "Run Terraform Format"
        run: terraform fmt

      - name: 'Terraform Apply'
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        

      
      



     

      
        
        
        



  

   