name: Deploy to Azure

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environrment"
        required: true
        type: environment
      resource_group:
        description: "Enter a resource group name"
        required: true
        type: string 
      resource_location:
        description: "where would you like the resources built"
        required: true
        type: string
      database_count:
        description: "How many databases would you like?"
        required: true
        type: choice
        default: "1"
        options:
          - 1
          - 2
          - 3
          - 4

        

permissions:
   id-token: write
   contents: read
   
env:
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    TF_VAR_admin_login: ${{ secrets.ADMIN_LOGIN }}
    TF_VAR_admin_login_password: ${{ secrets.ADMIN_LOGIN_PASSWORD }}
    TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
jobs:

  deploy-infrastructure:

    name: "Install Terraform and Azure ClI and Authenticate to Azure"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: "Checkout GitHub Repo"
        uses: actions/checkout@v4

      - name: set environement variable
        run: |
          echo "TF_VAR_name=${{ inputs.resource_group }}" >> $GITHUB_ENV
          echo "TF_VAR_database_count=${{ inputs.database_count }}" >> $GITHUB_ENV
          echo "TF_VAR_location=${{ inputs.resource_location }}" >> $GITHUB_ENV

      - name: "Login to Azure"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: "Install terraform on runner"
        uses: hashicorp/setup-terraform@v3

      - name: "Run Terraform init"
        run: terraform -chdir=Environments/${{ inputs.environment }} init
        env:
          TF_VAR_resource_group:  ${{ inputs.resource_group }}
        
      - name: "Run Terraform plan"
        run: terraform -chdir=Environments/${{ inputs.environment }} plan -out=tfplan
        env:
          TF_VAR_resource_group:  ${{ inputs.resource_group }}
        
          
      - name: "Run Terraform Format"
        run: terraform -chdir=Environments/${{ inputs.environment }} fmt
        env:
          TF_VAR_resource_group:  ${{ inputs.resource_group }} 
        

      - name: 'Terraform Apply'
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=Environments/${{ inputs.environment }} apply -auto-approve tfplan
        env:
          TF_VAR_resource_group:  ${{ inputs.resource_group }} 
        
       
        

      
      



     

      
        
        
        



  

   