name: Terraform Cleanup

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environrment"
        required: true
        default: "test"
        type: environment
      

env:
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    TF_VAR_admin_login: ${{ secrets.ADMIN_LOGIN }}
    TF_VAR_admin_login_password: ${{ secrets.ADMIN_LOGIN_PASSWORD }}
jobs:
  terraform-cleanup:
    name: 'Post Apply Cleanup'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    permissions:
      id-token: write
      contents: read

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v4

    - name: "Login to Azure"
      uses: azure/login@v2
      with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         secret-id: ${{ secrets.AZURE_SECRET_ID }}

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v3


    - name: 'Terraform Init'
      run: terraform init

      
    - name: 'Terraform Plan Destroy'
      run: terraform plan -destroy -out=tfplan-destroy

    - name: 'Terraform Apply Destroy'
      run: terraform destroy -auto-approve 

    
      