name: Terraform Cleanup

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environrment"
        required: true
        default: "test"
        type: choice
        options:
          - dev
          - test

jobs:
  terraform-cleanup:
    name: 'Post Apply Cleanup'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    permissions:
      id-token: write
      contents: read

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v4

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         secret-id: ${{ secrets.AZURE_SECRET_ID }}

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "latest"

    - name: 'Terraform Init'
      run: terraform init
      env:
          TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      

    - name: 'Terraform Plan Destroy'
      run: terraform plan -destroy -out=tfplan-destroy

    - name: 'Terraform Apply Destroy'
      run: terraform destroy -auto-approve 
    
      