name: Terraform Cleanup

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environrment"
        required: true
        default: "test"
        type: environment
        
      resource_group:
        description: "Enter a resource group name"
        required: true
        type: string   

      resource_location:
        description: "Resource location"
        required: true
        default: "eastus"
        type: string
permissions:
    id-token: write
    contents: read
    

env:
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    TF_VAR_admin_login: ${{ secrets.ADMIN_LOGIN }}
    TF_VAR_admin_login_password: ${{ secrets.ADMIN_LOGIN_PASSWORD }}
    TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:

  terraform-cleanup:
    name: 'Post Apply Cleanup'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v4

    - name: set environement variable
      run: |
          echo "TF_VAR_name=${{ inputs.resource_group }}" >> $GITHUB_ENV
          echo "TF_VAR_location=${{ inputs.resource_location }}" >> $GITHUB_ENV
          
  


    - name: "Login to Azure"
      uses: azure/login@v2
      with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v3


    - name: 'Terraform Init'
      run: terraform -chdir=Environments/${{ inputs.environment }} init

      
    - name: 'Terraform Plan Destroy'
      run: terraform -chdir=Environments/${{ inputs.environment }} plan -destroy -out=tfplan-destroy

    - name: 'Terraform Apply Destroy'
      run: terraform -chdir=Environments/${{ inputs.environment }} destroy -auto-approve 

    
      