name: Main Workflow
on:

  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

  
jobs: 
 
    test:
      uses: ./.github/workflows/test.yml
    
    deploy:
      uses: ./.github/workflows/deploy.yml
      needs: test