name: TFSec Test

on: 
  workflow_call:


jobs:
    # Run TfSec test against terraform config
    tfsec_scan:
        name: Run TfSec Scan
        runs-on: ubuntu-latest

        steps:

        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: tfsec
          uses: aquasecurity/tfsec-action@v1.0.0
          with:
            soft_fail: true
    
    trivy_scan:
        name: Trivy Scan for IaC
        runs-on: ubuntu-latest

        steps:
        
        - name: Checkout Repo
          uses: aquasecurity/trivy-action@0.28.0
          with:
            scan-type: 'config'
            hide-progress: true
            format: 'sarif'
            output: 'trivy-results.sarif'
            exit-code: '1'
            severity: 'CRITICAL,HIGH'

        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: 'trivy-results.sarif'

    snyk_scan:
      name: Run Snyk to check Terraform config for issues
      runs-on: ubuntu-latest

      steps:

      - name: checkout 
        uses: actions/checkout@v4

      - name: Setup Snyk
        run: npm install -g snyk


      - name: Snyk IaC
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 

      
      - name: Run Snyk Test
        run: snyk test -d
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

